# Generated by Django 5.1.2 on 2024-11-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tide', '0002_remove_profile_image_url_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='This is where you can add a bio or description about the user.'),
        ),
    ]
