# Generated by Django 5.1.2 on 2024-11-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tide', '0005_statusmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='status_images/'),
        ),
    ]
