# Generated by Django 5.1.2 on 2024-11-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tide', '0009_remove_statusmessage_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
