# Generated by Django 5.1.2 on 2024-11-13 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tide', '0011_surfspot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surfspot',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='SurfSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('wave_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('notes', models.TextField(blank=True)),
                ('surf_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surf_sessions', to='tide.surfspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surf_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
