# Generated by Django 5.1.2 on 2024-11-13 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tide', '0012_alter_surfspot_options_surfsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='surf_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tide.surfsession'),
        ),
        migrations.AlterField(
            model_name='surfsession',
            name='notes',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
