# Generated by Django 5.1.2 on 2024-11-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tide', '0014_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
    ]
